services:
  # 1. API
  constructix_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: constructix_api
    ports:
      - "5000:8080" # Brauzer localhost:5000 
    environment:
      # PostgreSql baglantisi ucun
      - ConnectionStrings__DefaultConnection=Host=constructix_db;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      # Redis baglantisi (Konteyner adi ile)
      - ConnectionStrings__Redis=${REDIS_HOST}:${REDIS_PORT},password=${REDIS_PASSWORD}
      # JWT secret keyini buradan oxuyacaq
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
    depends_on:
      - constructix_db
      - constructix_redis
    networks:
      - constructix_network
    restart: always

  # 2. Database
  constructix_db:
    image: postgres:latest
    container_name: constructix_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - constructix_db_new_volume:/var/lib/postgresql
    networks:
      - constructix_network
    restart: always

  # 3. Database (PGADMIN)
  pgadmin:
    image: dpage/pgadmin4
    container_name: constructix_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - constructix_db
    networks:
      - constructix_network
    restart: always
  # 4. Redis
  constructix_redis:
    image: redis:7.0-alpine
    container_name: constructix_redis
    # Sifreni burada aktiv edirik:
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - constructix_redis_data:/data
    networks:
      - constructix_network
    restart: always

  # 5. Redis Insight (Vizual idareetme ucun)
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: constructix_redis_insight
    ports:
      - "8001:8001"
    networks:
      - constructix_network
    restart: always

networks:
  constructix_network:
    driver: bridge

volumes:
  constructix_db_new_volume:
  constructix_redis_data: